/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reportefe;

import java.util.Scanner;
import javax.sql.rowset.CachedRowSet;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author acomercial05
 */
public class FE extends javax.swing.JFrame {

    /**
     * Creates new form FE
     */
    public FE() {
        initComponents();
        this.setExtendedState(FE.MAXIMIZED_BOTH);
        consultarProceso();
    }
    //Variables
    int p=0,Q=0,C=0,CTH=0,QUE=0,S=0,E=0,R=0,M=0;
    
    private void consultarProceso() {
        try {
            ProyectoController obj = new ProyectoController();
            CachedRowSet crs = obj.consultarProceso();
            JButton botn=new JButton();
            while (crs.next()) {
                //Pendinte
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPMaquinas = new javax.swing.JPanel();
        jPPerforado = new javax.swing.JPanel();
        jPQuimicos = new javax.swing.JPanel();
        jPCaminos = new javax.swing.JPanel();
        jPCCTH = new javax.swing.JPanel();
        jPQuemado = new javax.swing.JPanel();
        jPScreen = new javax.swing.JPanel();
        jPEstañado = new javax.swing.JPanel();
        jPCC2 = new javax.swing.JPanel();
        jPRuteo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Perforado");
        jLabel1.setToolTipText("Proceso");
        jLabel1.setPreferredSize(new java.awt.Dimension(138, 40));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Quimicos");
        jLabel2.setToolTipText("Proceso");
        jLabel2.setPreferredSize(new java.awt.Dimension(138, 40));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("C.C.TH");
        jLabel3.setToolTipText("Proceso");
        jLabel3.setPreferredSize(new java.awt.Dimension(138, 40));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Caminos");
        jLabel4.setToolTipText("Proceso");
        jLabel4.setPreferredSize(new java.awt.Dimension(138, 40));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Estañado");
        jLabel5.setToolTipText("Proceso");
        jLabel5.setPreferredSize(new java.awt.Dimension(138, 40));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Quemado");
        jLabel6.setToolTipText("Proceso");
        jLabel6.setPreferredSize(new java.awt.Dimension(138, 40));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("C.C2");
        jLabel7.setToolTipText("Proceso");
        jLabel7.setPreferredSize(new java.awt.Dimension(138, 40));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 140, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Ruteo");
        jLabel8.setToolTipText("Proceso");
        jLabel8.setPreferredSize(new java.awt.Dimension(138, 40));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Screen");
        jLabel9.setToolTipText("Proceso");
        jLabel9.setPreferredSize(new java.awt.Dimension(138, 40));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Maquinas");
        jLabel10.setToolTipText("Proceso");
        jLabel10.setPreferredSize(new java.awt.Dimension(138, 40));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, -1, -1));

        jPMaquinas.setBackground(new java.awt.Color(255, 255, 255));
        jPMaquinas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPMaquinasLayout = new javax.swing.GroupLayout(jPMaquinas);
        jPMaquinas.setLayout(jPMaquinasLayout);
        jPMaquinasLayout.setHorizontalGroup(
            jPMaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        jPMaquinasLayout.setVerticalGroup(
            jPMaquinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        jPanel1.add(jPMaquinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 40, 140, 670));

        jPPerforado.setBackground(new java.awt.Color(255, 255, 255));
        jPPerforado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPPerforadoLayout = new javax.swing.GroupLayout(jPPerforado);
        jPPerforado.setLayout(jPPerforadoLayout);
        jPPerforadoLayout.setHorizontalGroup(
            jPPerforadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        jPPerforadoLayout.setVerticalGroup(
            jPPerforadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        jPanel1.add(jPPerforado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 140, 670));

        jPQuimicos.setBackground(new java.awt.Color(255, 255, 255));
        jPQuimicos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPQuimicosLayout = new javax.swing.GroupLayout(jPQuimicos);
        jPQuimicos.setLayout(jPQuimicosLayout);
        jPQuimicosLayout.setHorizontalGroup(
            jPQuimicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        jPQuimicosLayout.setVerticalGroup(
            jPQuimicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        jPanel1.add(jPQuimicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 140, 670));

        jPCaminos.setBackground(new java.awt.Color(255, 255, 255));
        jPCaminos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPCaminosLayout = new javax.swing.GroupLayout(jPCaminos);
        jPCaminos.setLayout(jPCaminosLayout);
        jPCaminosLayout.setHorizontalGroup(
            jPCaminosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        jPCaminosLayout.setVerticalGroup(
            jPCaminosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        jPanel1.add(jPCaminos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 140, 670));

        jPCCTH.setBackground(new java.awt.Color(255, 255, 255));
        jPCCTH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPCCTHLayout = new javax.swing.GroupLayout(jPCCTH);
        jPCCTH.setLayout(jPCCTHLayout);
        jPCCTHLayout.setHorizontalGroup(
            jPCCTHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        jPCCTHLayout.setVerticalGroup(
            jPCCTHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        jPanel1.add(jPCCTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 140, 670));

        jPQuemado.setBackground(new java.awt.Color(255, 255, 255));
        jPQuemado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPQuemadoLayout = new javax.swing.GroupLayout(jPQuemado);
        jPQuemado.setLayout(jPQuemadoLayout);
        jPQuemadoLayout.setHorizontalGroup(
            jPQuemadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        jPQuemadoLayout.setVerticalGroup(
            jPQuemadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        jPanel1.add(jPQuemado, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 140, 670));

        jPScreen.setBackground(new java.awt.Color(255, 255, 255));
        jPScreen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPScreenLayout = new javax.swing.GroupLayout(jPScreen);
        jPScreen.setLayout(jPScreenLayout);
        jPScreenLayout.setHorizontalGroup(
            jPScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        jPScreenLayout.setVerticalGroup(
            jPScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        jPanel1.add(jPScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 140, 670));

        jPEstañado.setBackground(new java.awt.Color(255, 255, 255));
        jPEstañado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPEstañadoLayout = new javax.swing.GroupLayout(jPEstañado);
        jPEstañado.setLayout(jPEstañadoLayout);
        jPEstañadoLayout.setHorizontalGroup(
            jPEstañadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        jPEstañadoLayout.setVerticalGroup(
            jPEstañadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        jPanel1.add(jPEstañado, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, 140, 670));

        jPCC2.setBackground(new java.awt.Color(255, 255, 255));
        jPCC2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPCC2Layout = new javax.swing.GroupLayout(jPCC2);
        jPCC2.setLayout(jPCC2Layout);
        jPCC2Layout.setHorizontalGroup(
            jPCC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        jPCC2Layout.setVerticalGroup(
            jPCC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        jPanel1.add(jPCC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 140, 670));

        jPRuteo.setBackground(new java.awt.Color(255, 255, 255));
        jPRuteo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPRuteoLayout = new javax.swing.GroupLayout(jPRuteo);
        jPRuteo.setLayout(jPRuteoLayout);
        jPRuteoLayout.setHorizontalGroup(
            jPRuteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        jPRuteoLayout.setVerticalGroup(
            jPRuteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        jPanel1.add(jPRuteo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 40, 140, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPCC2;
    private javax.swing.JPanel jPCCTH;
    private javax.swing.JPanel jPCaminos;
    private javax.swing.JPanel jPEstañado;
    private javax.swing.JPanel jPMaquinas;
    private javax.swing.JPanel jPPerforado;
    private javax.swing.JPanel jPQuemado;
    private javax.swing.JPanel jPQuimicos;
    private javax.swing.JPanel jPRuteo;
    private javax.swing.JPanel jPScreen;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
