/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reportegenerarcoltime;

import javax.sql.rowset.CachedRowSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author comunicaciones03
 */
public class ReporteColtime extends javax.swing.JFrame {

    /**
     * Creates new form ReporteColtime
     */
    public ReporteColtime() {
        initComponents();
        this.setExtendedState(ReporteColtime.MAXIMIZED_BOTH);
        jTInforme.getTableHeader().setReorderingAllowed(false);
        InformeGeneralEmpresaColcircuitos();
    }
    //Variables
    CachedRowSet crs = null;
    String namesHeader[] = {"N°Orden", "Cliente", "Proyecto", "U.Negocio", "F.Ingreso", "FEE", "Proceso", "% Proyecto", "Estado", "NFEE", "Parada"};
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //Variables
    String orden = "";
    int rep = 0, parada = 0;
    Object v[] = new Object[11];
    DefaultTableModel df = new DefaultTableModel(null, namesHeader);

    /*
    orden=0
    cliente=1;
    proyecto=2;
    U.negocio=3;
    F.Ingreso=4;
    FEE=5;
    Proceso=6;
    % Proyecto=7;
    Estado=8;
    NFEE=9;
    Parada=10;
     */
    //--------------------------------------------------------------------------
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTInforme = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTInforme = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        jTInforme.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTInforme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "N°Orden", "Cliente", "N.Negocio", "F.ingreso", "FEE", "Proceso", "% proyecto", "Estado", "NFEE"
            }
        ));
        jTInforme.setFocusable(false);
        jTInforme.setGridColor(new java.awt.Color(255, 255, 255));
        jTInforme.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTInforme.setRowHeight(50);
        jScrollPane1.setViewportView(jTInforme);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void InformeGeneralEmpresaColcircuitos() {
        Modelo obj = new Modelo();
        try {
            crs = obj.informacionInformeGeneral();
            while (crs.next()) {
                if (rep == 0) {
                    vectorInicial();//Inicio del vector
                    rep = 1;
                } else {
                    if (!v[0].toString().equals(crs.getString(1))) {//Si el numero de orden es diferente a la que se guardo en el vector va a calcular el porcentaje y el proceso donde se encuentra la mayor cantidad de productos
                        //%...
                        //Cantidad Proceso
                        //Ingreso de vector a la tabla 
                        df.addRow(v);
                    } else {
                        vectorInicial();//Inicio del vector
                        rep = 1;
                    }
                }
            }
            //%...
            //Cantidad Proceso
            df.addRow(v);
            jTInforme.setModel(df);//Se agrega el modelo a la tabla

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }

    private void vectorInicial() {
        try {
            v[0] = crs.getString(1);//Oreden
            v[1] = crs.getString(3);//Nombre cliente
            v[2] = crs.getString(4);//Nombre Proyecto
            v[4] = crs.getString(7);//Ingreso
            v[5] = crs.getString(8);//FEE
            if (crs.getString(9) != null) {
                v[8] = crs.getString(18);//Estado
            } else {
                v[8] = "Por iniciar";//Estado
            }
            v[10]=crs.getString(2);
            v[9]=crs.getString(19);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e);
        }
    }

//------------------------------------------------------------------------------
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteColtime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteColtime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteColtime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteColtime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteColtime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTInforme;
    // End of variables declaration//GEN-END:variables
}
